In [9]:
import pandas as pd

# 1. Data Overview

## 1.1 Restaurants Dataset (Entity Clustering)

size: 864

matches: 112

In [18]:
df_restaurants = pd.read_csv("../data/restaurants.csv")

df_restaurants.head()

,name,address,city,phone,category,cluster
0,arnie morton's of chicago,435 s. la cienega blv.,los angeles,310/246-1501,american,0
1,arnie morton's of chicago,435 s. la cienega blvd.,los angeles,310-246-1501,steakhouses,0
2,art's delicatessen,12224 ventura blvd.,studio city,818/762-1221,american,1
3,art's deli,12224 ventura blvd.,studio city,818-762-1221,delis,1
4,hotel bel-air,701 stone canyon rd.,bel air,310/472-1211,californian,2

In [8]:
# Separating into two dataframes
duplicated_restaurant_mask = df_restaurants.duplicated(subset=['cluster'], keep='first')

df_restaurants_1 = df_restaurants[~duplicated_restaurant_mask]
df_restaurants_2 = df_restaurants[duplicated_restaurant_mask]

df_restaurants_1.head()

,name,address,city,phone,category,cluster
0,arnie morton's of chicago,435 s. la cienega blv.,los angeles,310/246-1501,american,0
2,art's delicatessen,12224 ventura blvd.,studio city,818/762-1221,american,1
4,hotel bel-air,701 stone canyon rd.,bel air,310/472-1211,californian,2
6,cafe bizou,14016 ventura blvd.,sherman oaks,818/788-3536,french,3
8,campanile,624 s. la brea ave.,los angeles,213/938-1447,american,4

## 1.2 DBLP and Scholar Dataset (Binary Entity Resolution)

size: 2616 x 64263

matches: 5347

In [30]:
df_dblp = pd.read_csv("../data/dblp-scholar/dblp.csv", encoding='latin1')
df_scholar = pd.read_csv("../data/dblp-scholar/scholar.csv")
df_dblp_scholar_matches = pd.read_csv("../data/dblp-scholar/matches.csv")

df_scholar.head()

,id,title,authors,venue,year
0,aKcZKwvwbQwJ,11578 Sorrento Valley Road,QD Inc,"San Diego,",NaN
1,ixKfiTHoaDoJ,Initiation of crazes in polystyrene,"AS Argon, JG Hannoosh","Phil. Mag,",NaN
2,3BxllB4wwcIJ,Immunogold labelling is a quantitative method ...,"GH Hansen, LL Wetterberg, H SjÃ¶strÃ¶m, O NorÃ©n","The Histochemical Journal,",1992.0
3,d2WWxwKMex4J,The Burden of Infectious Disease Among Inmates...,"TM Hammett, P Harmon, W Rhodes",see,NaN
4,cZCX-AQpjccJ,The Role of Faculty Advising in Science and En...,JR Cogdell,"NEW DIRECTIONS FOR TEACHING AND LEARNING,",1995.0

## 1.3 North Carolina Voters Dataset (Entity Clustering)

size: 5 Millions (1 million each file)

In [33]:
# Store the reference to the dataframes in a list (not the entire dataframes)
df_nc_voters = [pd.read_csv(f"../data/north_carolina_voters/dataset_{i}.csv") for i in range(1, 6)]

C:\Users\leove\AppData\Local\Temp\ipykernel_9404\179556799.py:2: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df_nc_voters = [pd.read_csv(f"../data/north_carolina_voters/dataset_{i}.csv") for i in range(1, 6)]
C:\Users\leove\AppData\Local\Temp\ipykernel_9404\179556799.py:2: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df_nc_voters = [pd.read_csv(f"../data/north_carolina_voters/dataset_{i}.csv") for i in range(1, 6)]
C:\Users\leove\AppData\Local\Temp\ipykernel_9404\179556799.py:2: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df_nc_voters = [pd.read_csv(f"../data/north_carolina_voters/dataset_{i}.csv") for i in range(1, 6)]
C:\Users\leove\AppData\Local\Temp\ipykernel_9404\179556799.py:2: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df_nc_voters = [pd.read_csv(f"../data/north_carolina_voters/dataset_{i}.csv") for i in range(1, 6)]
C:\Users\leove\AppData\Local\Temp\ipykernel_9404\179556799.py:2: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df_nc_voters = [pd.read_csv(f"../data/north_carolina_voters/dataset_{i}.csv") for i in range(1, 6)]

In [32]:
df_nc_voters[0].head()

     recid givenname   surname         suburb postcode
0  7852009   kadelyn  gragnani         waxhaw    28|73
1  3138435     ronel    carter     washington    2788g
2  6117295     jason   roehrig  millers ceeek    286s1
3  6401695    antrea      mure     greensboro    27410
4  5202204    caedar    oliver   jacksonville    28542

# 2. Record Linkage